import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F5F1EB] text-[#2F2F2F]`}>

  <header className="flex justify-between items-center px-10 py-8 max-w-7xl mx-auto">

  <div className="text-lg tracking-[0.2em] font-medium">
    LITE ORBIT
  </div>

  <nav className="space-x-10 text-sm text-[#6B6B6B]">
    <a href="#" className="hover:text-black transition duration-300">Home</a>
    <a href="#" className="hover:text-black transition duration-300">About</a>
    <a href="#" className="hover:text-black transition duration-300">Collection</a>
    <a href="#" className="hover:text-black transition duration-300">Contact</a>
  </nav>

</header>

  {children}

<footer className="py-16 px-10 bg-[#E7E2DA] mt-24">
  <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center text-sm text-[#6B6B6B]">
    
    <div className="tracking-[0.2em] mb-6 md:mb-0">
      LITE ORBIT
    </div>

    <div className="space-x-8">
      <a href="#" className="hover:text-black transition">Privacy</a>
      <a href="#" className="hover:text-black transition">Terms</a>
      <a href="#" className="hover:text-black transition">Contact</a>
    </div>

  </div>
  </footer>

</body>
    </html>
  );
}
